### ISSUE TITLE
Crash when going to TheBetweenLands

### ISSUE THREAD

**Issue by insuusvenerati** [insuusvenerati/forbidden-mc#2]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b150.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  VanillaFixLoadingPlugin (VanillaFix-1.0.6-53.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  OTGCorePlugin (OTG-Core.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.22.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 5/29/18 4:07 PM
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: erebus.recipes.RecipePaxel@2ebb906a Name: erebus:recipe_paxel
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.minecraft.util.Util.runTask(SourceFile:530)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1086)
	at net.minecraft.client.Minecraft.run(Minecraft.java:3911)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: erebus.recipes.RecipePaxel@2ebb906a Name: erebus:recipe_paxel
	at net.minecraft.stats.RecipeBook.func_194075_d(RecipeBook.java:53)
	at net.minecraft.stats.RecipeBook.func_193830_f(RecipeBook.java:35)
	at net.minecraft.client.gui.recipebook.RecipeList.func_194214_a(SourceFile:27)
	at net.minecraft.client.network.NetHandlerPlayClient.lambda$handleRecipeBook$2(NetHandlerPlayClient.java:1487)
	at net.minecraft.client.network.NetHandlerPlayClient$$Lambda$2301/1907508946.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraft.client.network.NetHandlerPlayClient.func_191980_a(NetHandlerPlayClient.java:1485)
	at net.minecraft.network.play.server.SPacketRecipeBook.func_148833_a(SourceFile:39)
	at net.minecraft.network.play.server.SPacketRecipeBook.func_148833_a(SourceFile:12)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:528)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3911)
	... 7 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2243807840 bytes (2139 MB) / 5085069312 bytes (4849 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.3.2697 150 mods loaded, 150 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                        | Version                      | Source                                              | Signature                                |
	|:------ |:------------------------- |:---------------------------- |:--------------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft                 | 1.12.2                       | minecraft.jar                                       | None                                     |
	| UCHIJA | mcp                       | 9.42                         | minecraft.jar                                       | None                                     |
	| UCHIJA | FML                       | 8.0.99.99                    | forge-1.12.2-14.23.3.2697.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                     | 14.23.3.2697                 | forge-1.12.2-14.23.3.2697.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | otgcore                   | 1.12.2 - v7                  | minecraft.jar                                       | None                                     |
	| UCHIJA | foamfixcore               | 7.7.4                        | minecraft.jar                                       | None                                     |
	| UCHIJA | jei                       | 4.9.1.191                    | jei_1.12.2-4.9.1.191.jar                            | None                                     |
	| UCHIJA | abyssalcraft              | 1.9.4.9                      | AbyssalCraft-1.12.2-1.9.4.9.jar                     | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCHIJA | actuallyadditions         | 1.12.2-r135                  | ActuallyAdditions-1.12.2-r135.jar                   | None                                     |
	| UCHIJA | craftstudioapi            | 1.0.0                        | CraftStudio-1.0.0.93-mc1.12-alpha.jar               | None                                     |
	| UCHIJA | quark                     | r1.4-123                     | Quark-r1.4-123.jar                                  | None                                     |
	| UCHIJA | animania                  | 1.4.7                        | animania-1.12.2-1.4.8.jar                           | None                                     |
	| UCHIJA | mantle                    | 1.12-1.3.2.24                | Mantle-1.12-1.3.2.24.jar                            | None                                     |
	| UCHIJA | ctm                       | MC1.12-0.2.3.12              | CTM-MC1.12-0.2.3.12.jar                             | None                                     |
	| UCHIJA | chisel                    | MC1.12.2-0.2.0.31            | Chisel-MC1.12.2-0.2.0.31.jar                        | None                                     |
	| UCHIJA | tconstruct                | 1.12.2-2.10.0.81             | TConstruct-1.12.2-2.10.0.81.jar                     | None                                     |
	| UCHIJA | thedragonlib              | 1.12.2-5.2.0                 | thedragonlib-1.12.2-5.2.0.jar                       | None                                     |
	| UCHIJA | armorplus                 | 1.12.2-11.13.0.40            | armorplus-1.12.2-11.13.0.40.jar                     | None                                     |
	| UCHIJA | aroma1997core             | 2.0.0.0.b150                 | Aroma1997Core-1.12.2-2.0.0.0.b150.jar               | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJA | aroma1997sdimension       | 2.0.0.2.b69                  | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b69.jar | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJA | autoreglib                | 1.3-17                       | AutoRegLib-1.3-17.jar                               | None                                     |
	| UCHIJA | ichunutil                 | 7.1.4                        | iChunUtil-1.12.2-7.1.4.jar                          | None                                     |
	| UCHIJA | backtools                 | 7.0.0                        | BackTools-1.12.2-7.0.0.jar                          | None                                     |
	| UCHIJA | badwithernocookiereloaded | 1.12.2-2.12                  | badwithernocookiereloaded-1.12.2-2.12.jar           | None                                     |
	| UCHIJA | base                      | 3.7.2                        | base-1.12.2-3.7.2.jar                               | None                                     |
	| UCHIJA | baubles                   | 1.5.2                        | Baubles-1.12-1.5.2.jar                              | None                                     |
	| UCHIJA | betterbuilderswands       | 0.11.1                       | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar     | None                                     |
	| UCHIJA | betterquesting            | 3.5.257                      | BetterQuesting-3.5.257.jar                          | None                                     |
	| UCHIJA | bibliocraft               | 2.4.4                        | BiblioCraft[v2.4.4][MC1.12.2].jar                   | None                                     |
	| UCHIJA | openterraingenerator      | v6                           | OpenTerrainGenerator-1.12.2 - v6.jar                | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
	| UCHIJA | biomebundle               | 5.1                          | Biome_Bundle-1.12.2-v6.1.jar                        | None                                     |
	| UCHIJA | guideapi                  | 1.12-2.1.5-60                | Guide-API-1.12-2.1.5-60.jar                         | None                                     |
	| UCHIJA | bloodmagic                | 1.12.2-2.2.12-97             | BloodMagic-1.12.2-2.2.12-97.jar                     | None                                     |
	| UCHIJA | bloodmoon                 | 1.5.3                        | Bloodmoon-MC1.12.2-1.5.3.jar                        | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJA | codechickenlib            | 3.1.8.341                    | CodeChickenLib-1.12.2-3.1.8.341-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | redstoneflux              | 2.0.1                        | RedstoneFlux-1.12-2.0.1.2-universal.jar             | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJA | brandonscore              | 2.4.2                        | BrandonsCore-1.12-2.4.2.157-universal.jar           | None                                     |
	| UCHIJA | mcmultipart               | 2.5.1                        | MCMultiPart-2.5.1.jar                               | None                                     |
	| UCHIJA | cofhcore                  | 4.4.1                        | CoFHCore-1.12.2-4.4.1.12-universal.jar              | None                                     |
	| UCHIJA | computercraft             | 1.80pr1                      | ComputerCraft1.80pr1.jar                            | None                                     |
	| UCHIJA | mekanism                  | 1.12.2-9.4.10.345            | Mekanism-1.12.2-9.4.10.345.jar                      | None                                     |
	| UCHIJA | sonarcore                 | 5.0.9                        | sonarcore-1.12.2-5.0.9.jar                          | None                                     |
	| UCHIJA | calculator                | 5.0.4                        | calculator-1.12.2-5.0.4.jar                         | None                                     |
	| UCHIJA | chameleon                 | 1.12-4.1.3                   | Chameleon-1.12-4.1.3.jar                            | None                                     |
	| UCHIJA | clienttweaks              | 3.1.8                        | ClientTweaks_1.12.2-3.1.8.jar                       | None                                     |
	| UCHIJA | clumps                    | 2.0.0                        | Clumps-3.0.0.jar                                    | None                                     |
	| UCHIJA | cofhworld                 | 1.1.1                        | CoFHWorld-1.12.2-1.1.1.12-universal.jar             | None                                     |
	| UCHIJA | combustfish               | 1.0.3.2                      | combustfish-1.12.2-1.0.3.2.jar                      | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJA | storagedrawers            | 1.12-5.3.5                   | StorageDrawers-1.12.2-5.3.6.jar                     | None                                     |
	| UCHIJA | refinedstorage            | 1.5.34                       | refinedstorage-1.5.34.jar                           | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCHIJA | compactmachines3          | 3.0.11                       | compactmachines3-1.12.2-3.0.11-b207.jar             | None                                     |
	| UCHIJA | conarm                    | 0.0.19-b                     | conarm-1.12.2-0.0.19-b.jar                          | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJA | controlling               | 3.0.6                        | Controlling-3.0.6.jar                               | None                                     |
	| UCHIJA | craftingtweaks            | 8.1.9                        | CraftingTweaks_1.12.2-8.1.9.jar                     | None                                     |
	| UCHIJA | creeperconfetti           | 1.4.2                        | creeperconfetti-1.4.2.jar                           | None                                     |
	| UCHIJA | cyclopscore               | 0.11.6                       | CyclopsCore-1.12.2-0.11.6.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJA | ptrmodellib               | 1.0.2                        | PTRLib-1.0.2.jar                                    | None                                     |
	| UCHIJA | props                     | 2.6.0                        | Decocraft-2.6.0_1.12.2.jar                          | None                                     |
	| UCHIJA | cdm                       | 0.4.1                        | device-mod-0.4.1-1.12.2.jar                         | None                                     |
	| UCHIJA | dooglamoocitiesmod        | 1.6.3                        | dooglamoocitiesmod-1.12-1.6.3.jar                   | None                                     |
	| UCHIJA | dldungeonsjdg             | 1.11.1                       | DoomlikeDungeons-1.11.1-MC1.12.2.jar                | None                                     |
	| UCHIJA | thermalfoundation         | 2.4.1                        | ThermalFoundation-1.12.2-2.4.1.15-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | draconicevolution         | 2.3.11                       | Draconic-Evolution-1.12-2.3.11.290-universal.jar    | None                                     |
	| UCHIJA | dregora                   | 1.0                          | Dregora-1.12.2-v1.1.jar                             | None                                     |
	| UCHIJA | emberroot                 | 1.3.7                        | EmberRootZoo-1.12-1.3.7.jar                         | None                                     |
	| UCHIJA | embers                    | 0.230                        | embers-0.230.jar                                    | None                                     |
	| UCHIJA | enchdesc                  | 1.1.8                        | EnchantmentDescriptions-1.12.2-1.1.8.jar            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | endercore                 | 1.12.2-0.5.22                | EnderCore-1.12.2-0.5.22.jar                         | None                                     |
	| UCHIJA | enderzoo                  | 1.12.1-1.4.0.49              | EnderZoo-1.12.1-1.4.0.49.jar                        | None                                     |
	| UCHIJA | epicsiegemod              | 13.160                       | EpicSiegeMod-13.160.jar                             | None                                     |
	| UCHIJA | erebus                    | 1.0.22                       | Erebus-1.0.22.jar                                   | None                                     |
	| UCHIJA | evilcraft                 | 0.10.57                      | EvilCraft-1.12.2-0.10.57.jar                        | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJA | thaumcraft                | 6.1.BETA15                   | Thaumcraft-1.12.2-6.1.BETA15.jar                    | None                                     |
	| UCHIJA | evilcraftcompat           | 1.0.0                        | EvilCraft-1.12.2-0.10.57.jar                        | None                                     |
	| UCHIJA | extrautils2               | 1.0                          | extrautils2-1.12-1.7.6.jar                          | None                                     |
	| UCHIJA | foamfix                   | 0.9.9.1-1.12.2               | foamfix-0.9.9.1-1.12.2-anarchy.jar                  | None                                     |
	| UCHIJA | forgemultipartcbe         | 2.4.2.58                     | ForgeMultipart-1.12.2-2.4.2.58-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | microblockcbe             | 2.4.2.58                     | ForgeMultipart-1.12.2-2.4.2.58-universal.jar        | None                                     |
	| UCHIJA | minecraftmultipartcbe     | 2.4.2.58                     | ForgeMultipart-1.12.2-2.4.2.58-universal.jar        | None                                     |
	| UCHIJA | ftblib                    | 5.0.2.14                     | FTBLib-5.0.2.14.jar                                 | None                                     |
	| UCHIJA | ftbutilities              | 5.0.2.14                     | FTBUtilities-5.0.2.14.jar                           | None                                     |
	| UCHIJA | fp                        | 26.3.210                     | Futurepack-1.12.2-26.3.210.jar                      | 3ad693059337b95c41b649ec9f29c4a6e8282586 |
	| UCHIJA | fp.api                    | 1.1.0                        | Futurepack-1.12.2-26.3.210.jar                      | None                                     |
	| UCHIJA | gbook                     | 2.0.1                        | Guidebook-1.12.2-2.0.1.jar                          | None                                     |
	| UCHIJA | hats                      | 7.0.0                        | Hats-1.12.2-7.0.2.jar                               | None                                     |
	| UCHIJA | waila                     | 1.8.25                       | Hwyla-1.8.25-B40_1.12.jar                           | None                                     |
	| UCHIJA | immersiveengineering      | 0.12-82                      | ImmersiveEngineering-0.12-82.jar                    | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJA | immersivepetroleum        | 1.1.9                        | immersivepetroleum-1.12.2-1.1.9.jar                 | None                                     |
	| UCHIJA | immersivetech             | 1.3.9                        | immersivetech-1.12-1.3.9.jar                        | None                                     |
	| UCHIJA | instantunify              | 1.1.1                        | instantunify-1.12.2-1.1.1.jar                       | None                                     |
	| UCHIJA | inventorypets             | 1.4.9.9b                     | inventorypets-1.12-1.4.9.9b.jar                     | None                                     |
	| UCHIJA | inventorytweaks           | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA | ironbackpacks             | 1.12.2-3.0.8-12              | IronBackpacks-1.12.2-3.0.8-12.jar                   | None                                     |
	| UCHIJA | ironchest                 | 1.12.2-7.0.42.827            | ironchest-1.12.2-7.0.42.827.jar                     | None                                     |
	| UCHIJA | jeiintegration            | 1.5.1.36                     | jeiintegration_1.12.2-1.5.1.36.jar                  | None                                     |
	| UCHIJA | jeivillagers              | 1.0                          | jeivillagers-1.12-1.0.2.jar                         | None                                     |
	| UCHIJA | journeymap                | 1.12.2-5.5.2                 | journeymap-1.12.2-5.5.2.jar                         | None                                     |
	| UCHIJA | jeresources               | 0.8.7.41                     | JustEnoughResources-1.12.2-0.8.7.41.jar             | None                                     |
	| UCHIJA | lightningcraft            | 2.9.1                        | lightningcraft-2.9.1-[1.12.2].jar                   | None                                     |
	| UCHIJA | malisiscore               | 1.12.2-6.4.0                 | malisiscore-1.12.2-6.4.0.jar                        | None                                     |
	| UCHIJA | malisisdoors              | 1.12.2-7.3.0                 | malisisdoors-1.12.2-7.3.0.jar                       | None                                     |
	| UCHIJA | mekanismtools             | 9.4.10                       | MekanismTools-1.12.2-9.4.10.345.jar                 | None                                     |
	| UCHIJA | minecraftboom             | 1.4.0                        | minecraftboom-1.12.2-1.4.0-universal.jar            | None                                     |
	| UCHIJA | moartinkers               | 0.5.4                        | moartinkers-0.5.4.jar                               | None                                     |
	| UCHIJA | moreoverlays              | 1.13                         | moreoverlays-1.13-mc1.12.1.jar                      | None                                     |
	| UCHIJA | morpheus                  | 1.12-3.3.2                   | Morpheus-1.12-3.3.2.jar                             | None                                     |
	| UCHIJA | mousetweaks               | 2.8                          | MouseTweaks-2.8-mc1.12.1.jar                        | None                                     |
	| UCHIJA | mputils                   | 1.5.6                        | MPUtils-1.12.2-1.5.6.jar                            | None                                     |
	| UCHIJA | mpbasic                   | 1.4.7                        | mpbasic-1.12.2-1.4.8.jar                            | None                                     |
	| UCHIJA | neat                      | 1.4-15                       | Neat 1.4-15.jar                                     | None                                     |
	| UCHIJA | nex                       | 2.1.14.15                    | NetherEx-1.12-2.1.14.15.jar                         | None                                     |
	| UCHIJA | openglider                | @VERSION@                    | OpenGlider-1.12.1-1.1.0.jar                         | None                                     |
	| UCHIJA | oreexcavation             | 1.4.118                      | OreExcavation-1.4.118.jar                           | None                                     |
	| UCHIJA | plustic                   | 6.5.1.0                      | plustic-6.5.1.0.jar                                 | None                                     |
	| UCHIJA | practicallogistics2       | 3.0.3                        | practicallogistics2-1.12.2-3.0.3.jar                | None                                     |
	| UCHIJA | quickleafdecay            | 1.2.4                        | QuickLeafDecay-MC1.12.1-1.2.4.jar                   | None                                     |
	| UCHIJA | radixcore                 | 1.12.x-2.2.1                 | RadixCore-1.12.x-2.2.1-universal.jar                | None                                     |
	| UCHIJA | reborncore                | 3.8.3.279                    | RebornCore-1.12.2-3.8.3.279-universal.jar           | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJA | rebornstorage             | 1.0.0                        | RebornStorage-1.12.2-3.1.0.50.jar                   | None                                     |
	| UCHIJA | thermalexpansion          | 5.4.2                        | ThermalExpansion-1.12.2-5.4.2.27-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | redstonearsenal           | 2.4.2                        | RedstoneArsenal-1.12.2-2.4.2.9-universal.jar        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | refinedstorageaddons      | 0.3                          | refinedstorageaddons-0.3.jar                        | None                                     |
	| UCHIJA | roguelike                 | 1.8.0                        | RoguelikeDungeons-1.12.2-1.8.0.jar                  | None                                     |
	| UCHIJA | storagenetwork            | 1.12.2-1.2.4                 | SimpleStorageNetwork-1.12.2-1.2.4.jar               | None                                     |
	| UCHIJA | thermaldynamics           | 2.4.1                        | ThermalDynamics-1.12.2-2.4.1.10-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | simplyjetpacks            | 2.2.5.39                     | SimplyJetpacks2-1.12.2-2.2.5.39.jar                 | None                                     |
	| UCHIJA | spartanshields            | 1.4.1                        | SpartanShields-1.12.2-1.4.1.jar                     | None                                     |
	| UCHIJA | bq_standard               | 3.4.142                      | StandardExpansion-3.4.142.jar                       | None                                     |
	| UCHIJA | stg                       | 1.12.2-1.2.3                 | stg-1.12.2-1.2.3.jar                                | None                                     |
	| UCHIJA | tcinventoryscan           | 2.0.10                       | ThaumicInventoryScanning_1.12.2-2.0.10.jar          | None                                     |
	| UCHIJA | thaumicjei                | 1.2.1                        | ThaumicJEI-1.12.2-1.2.4-9.jar                       | None                                     |
	| UCHIJA | thaumicperiphery          | 0.2.3                        | thaumicperiphery-0.2.3.jar                          | None                                     |
	| UCHIJA | thebetweenlands           | 3.3.8                        | TheBetweenlands-3.3.8-universal.jar                 | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCHIJA | tcomplement               | ${version}                   | TinkersComplement-1.12.2-0.2.3b.jar                 | None                                     |
	| UCHIJA | tinkersjei                | 1.0                          | tinkersjei-1.0.jar                                  | None                                     |
	| UCHIJA | tinkertoolleveling        | 1.12-1.0.4.DEV.5d716b9       | TinkerToolLeveling-1.12-1.0.4.jar                   | None                                     |
	| UCHIJA | translocators             | 2.5.0.70                     | Translocators-1.12.2-2.5.0.70-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | usefulnullifiers          | 1.4.1                        | usefulnullifiers-1.4.1.jar                          | None                                     |
	| UCHIJA | vanillafix                | 1.0.6+53                     | VanillaFix-1.0.6-53.jar                             | None                                     |
	| UCHIJA | vc                        | 5.9.13                       | ViesCraft-1.12.2-5.9.13.jar                         | None                                     |
	| UCHIJA | wailaharvestability       | 1.1.12                       | WailaHarvestability-mc1.12-1.1.12.jar               | None                                     |
	| UCHIJA | wanionlib                 | 1.12.2-1.5                   | WanionLib-1.12.2-1.5.jar                            | None                                     |
	| UCHIJA | wawla                     | 2.5.256                      | Wawla-1.12.2-2.5.256.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | waystones                 | 4.0.43                       | Waystones_1.12.2-4.0.43.jar                         | None                                     |
	| UCHIJA | wearablebackpacks         | 3.1.2                        | WearableBackpacks-1.12.2-3.1.2.jar                  | None                                     |
	| UCHIJA | wolfarmor                 | 1.12.2-2.1.0-RELEASE         | wolfarmor-1.12.2-2.1.0.26-RELEASE.jar               | None                                     |
	| UCHIJA | woot                      | 1.12.2-1.2.1                 | woot-1.12.2-1.2.1.jar                               | None                                     |
	| UCHIJA | yoyos                     | 1.12.2-1.2.2.20              | yoyos_1.12.2-1.2.2.20.jar                           | None                                     |
	| UCHIJA | reauth                    | 3.6.0                        | reauth-3.6.0.jar                                    | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| UCHIJA | unidict                   | 1.12.2-2.5c                  | UniDict-1.12.2-2.5c.jar                             | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b150.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
VanillaFixLoadingPlugin (VanillaFix-1.0.6-53.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
LoadingPlugin (Quark-r1.4-123.jar)
  vazkii.quark.base.asm.ClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.22.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 397.31' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleFeature (Enabled/Not Forced)
		- ChiselPlugin (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.8.3.279
		Runtime Debofucsation 1
		RenderEngine: 0
	Suspected Mods: Unknown

**Comment by insuusvenerati** [comment]
Resolved with latest Minecraft Boom update.
